### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by hauschke** [mmannings/VIVO#1]
Documentation of all basic features. Place of the documentation has to be decided. VIVO wiki or here in the repo.

**Comment by mmannings** [comment]
Initial documentation about the main steps and functionalities are added under (currently under intra TIB forum)  
 https://wiki.tib.eu/confluence/display/tapir/Documentation+of+the+TAPIR+reporting+tool
 
 I will as well duplicate the documentation in the README.md of the VIVO and VItro in Tapir organization:
 https://github.com/Project-TAPIR/vivo-reporting
 https://github.com/Project-TAPIR/vitro-reporting
