### ISSUE TITLE
Construct query should always be provided and can't be skipped. 

### ISSUE THREAD

**Issue by hauschke** [mmannings/VIVO#2]
Construct query should always be provided and can't be skipped.

**Comment by mmannings** [comment]
Should be fixed via:
https://github.com/mmannings/VIVO/commit/6c2402a5448f0f934069df71d9875176185b70a5

**Comment by mmannings** [comment]
Solved, by splitting the _new report button_ with a drop down menu:
- Add new report with construct (will open the normal stepper with construct and other steps as usual);
- Add new report with only select (will open stepper with 3 steps: select, template, review). Construct is set to default in that case, which equals full_union in VIVO.

Closing for now. Later on, could be reopened, to handle the case of not sending _construct_queries_ param at all, though its doubtful, if needed to be done or could be left as is now.
