### ISSUE TITLE
Feedback for saving a report

### ISSUE THREAD

**Issue by hauschke** [mmannings/VIVO#3]
**Is your feature request related to a problem? Please describe.**
If one is trying to click on the button to save a report, there is no feedback. This results in clicking several times and not being aware, that the report has been saved several times.

**Describe the solution you'd like**
When saving a report, a message would be good, that it has been saved.

**Comment by mmannings** [comment]
Should be deployed.

**Comment by mmannings** [comment]
Closing. Feedback is provided for two states: success - report added, fail - report not added (error happened during creation).
