### ISSUE TITLE
.docx saved with wrong file extension

### ISSUE THREAD

**Issue by hauschke** [mmannings/VIVO#4]
**Describe the bug**
When trying to save a .docx report, it is saved with the wrong extension (.xlsx).

**To Reproduce**
1. Create a .docx-based report
2. Go to "list", click on download report
3. Investigate the file.

**Expected behavior**
A .docx file should be saved as such.

CC @tawahle @litvinovg @bkampe

**Comment by mmannings** [comment]
Should be fixed via:
https://github.com/mmannings/VIVO/commit/38dbfc76c45e04e1d739dbe0a1781aa7fae6acb1  
https://github.com/mmannings/VIVO/commit/c82b8509c70eede5c4a888df36d29023736e0c67
As well as already deployed to demo.

**Comment by mmannings** [comment]
Closing. File format will be picked dynamic from the provided template.
